name: Pre-release

on:
  push:
    branches: [master]
    paths-ignore:
      - '*.md'
      - '*.json'
      - '**/wcokey.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Google Services for Prerelease
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON_PRERELEASE }}" > $GITHUB_WORKSPACE/app/google-services.json

      - name: Print google-services.json for debugging
        run: cat $GITHUB_WORKSPACE/app/google-services.json

      - name: Validate google-services.json
        run: |
          if ! jq empty $GITHUB_WORKSPACE/app/google-services.json; then
            echo "Malformed google-services.json"
            exit 1
          fi
        shell: bash

      - name: Copy keystore to runner
        run: echo "${{ secrets.KEYSTORE_CONTENT }}" | base64 --decode > $RUNNER_TEMP/mostreamkey.jks

      - name: Verify keystore creation
        run: ls -la $RUNNER_TEMP

      - name: Run Gradle Build
        run: ./gradlew assemblePrereleaseRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-prerelease-release
          path: app/build/outputs/apk/prerelease/release/*.apk
